//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityListActivity
    {
        public ActivityListActivity()
        {
            this.UserActivities = new HashSet<UserActivity>();
        }
    
        public long ActivityListActivityId { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public Nullable<long> ActivityListId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivityList ActivityList { get; set; }
        public virtual ICollection<UserActivity> UserActivities { get; set; }
    }
}
