//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityList
    {
        public ActivityList()
        {
            this.ActivityListActivities = new HashSet<ActivityListActivity>();
            this.UserActivityLists = new HashSet<UserActivityList>();
        }
    
        public long ActivityListId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NumOfUsers { get; set; }
        public Nullable<int> NumOfActivity { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    
        public virtual ICollection<ActivityListActivity> ActivityListActivities { get; set; }
        public virtual ICollection<UserActivityList> UserActivityLists { get; set; }
    }
}
