//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BucketEntities : DbContext
    {
        public BucketEntities()
            : base("name=BucketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessToken> AccessTokens { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<ActivityList> ActivityLists { get; set; }
        public DbSet<ActivityListActivity> ActivityListActivities { get; set; }
        public DbSet<Friend> Friends { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserActivity> UserActivities { get; set; }
        public DbSet<UserActivityList> UserActivityLists { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
