//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.UserActivities = new HashSet<UserActivity>();
        }
    
        public long ReviewId { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Review1 { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserActivity> UserActivities { get; set; }
    }
}
