//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public long UserActivityId { get; set; }
        public Nullable<long> ActivityListActivityId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<long> ReviewId { get; set; }
    
        public virtual ActivityListActivity ActivityListActivity { get; set; }
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
    }
}
