//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AccessTokens = new HashSet<AccessToken>();
            this.Friends = new HashSet<Friend>();
            this.Friends1 = new HashSet<Friend>();
            this.Reviews = new HashSet<Review>();
            this.UserActivities = new HashSet<UserActivity>();
            this.UserActivityLists = new HashSet<UserActivityList>();
        }
    
        public long UsersId { get; set; }
        public string Email { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public string Zipcode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<AccessToken> AccessTokens { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual ICollection<Friend> Friends1 { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<UserActivity> UserActivities { get; set; }
        public virtual ICollection<UserActivityList> UserActivityLists { get; set; }
    }
}
